export const INITIAL_VILLAGES = [
  { id: 'chitri', name: 'चितरी' },
  { id: 'rampur', name: 'रामपुर' },
  { id: 'govindgarh', name: 'गोविंदगढ़' },
  { id: 'sundarpur', name: 'सुंदरपुर' },
  { id: 'kalyanpur', name: 'कल्याणपुर' },
];

export const INITIAL_CONTACTS = [
  {
    villageId: 'chitri',
    villageName: 'चितरी',
    name: 'रामलाल यादव',
    mobile: '9876543210',
    alternateMobile: '9876543211',
    category: 'किसान',
    address: 'वार्ड 2, पटेल चौक',
    remark: 'उन्नत जैविक खेती विशेषज्ञ',
  },
  {
    villageId: 'chitri',
    villageName: 'चितरी',
    name: 'रामेश्वर शर्मा',
    mobile: '9823456781',
    alternateMobile: '',
    category: 'किराना व्यापारी',
    address: 'मुख्य बाजार, डाकघर के पास',
    remark: 'थोक व खुदरा दैनिक सामग्री',
  },
  {
    villageId: 'chitri',
    villageName: 'चितरी',
    name: 'सुनीता देवी',
    mobile: '9765432190',
    alternateMobile: '',
    category: 'शिक्षिका',
    address: 'प्राथमिक विद्यालय रोड, वार्ड 4',
    remark: 'बालिका शिक्षा प्रेरक',
  },
  {
    villageId: 'chitri',
    villageName: 'चितरी',
    name: 'दिनेश प्रजापति',
    mobile: '9988776655',
    alternateMobile: '',
    category: 'कुम्हार / शिल्पी',
    address: 'कुम्हार मोहल्ला',
    remark: 'मिट्टी के बर्तन व कलाकृतियाँ',
  },
  {
    villageId: 'chitri',
    villageName: 'चितरी',
    name: 'मोहन सिंह',
    mobile: '9414567890',
    alternateMobile: '9414567899',
    category: 'डेयरी संचालक',
    address: 'दुग्ध संकलन केंद्र के सामने',
    remark: 'शुद्ध देशी गाय का दूध व घी',
  },
  {
    villageId: 'rampur',
    villageName: 'रामपुर',
    name: 'मुकेश कुमार',
    mobile: '9829012345',
    alternateMobile: '',
    category: 'कृषि यंत्र मिस्त्री',
    address: 'बस स्टैंड के पीछे',
    remark: 'ट्रैक्टर व ट्यूबवेल मोटर रिपेयरिंग',
  },
  {
    villageId: 'rampur',
    villageName: 'रामपुर',
    name: 'सीमा वर्मा',
    mobile: '9632587410',
    alternateMobile: '',
    category: 'सिलाई व बुटीक',
    address: 'माता जी मंदिर गली',
    remark: 'महिलाओं व बच्चों के परिधान',
  },
  {
    villageId: 'rampur',
    villageName: 'रामपुर',
    name: 'राजेश पटेल',
    mobile: '9871234560',
    alternateMobile: '9871234561',
    category: 'खाद-बीज विक्रेता',
    address: 'कृषि उपज मंडी मार्ग',
    remark: 'प्रमाणित बीज, कीटनाशक एवं जैविक खाद',
  },
  {
    villageId: 'govindgarh',
    villageName: 'गोविंदगढ़',
    name: 'हरिसिंह मीणा',
    mobile: '9460112233',
    alternateMobile: '',
    category: 'बढ़ई (कारपेंटर)',
    address: 'रेलवे फाटक के पास',
    remark: 'सागवान व शीशम के दरवाजे, चौखट',
  },
  {
    villageId: 'govindgarh',
    villageName: 'गोविंदगढ़',
    name: 'रेखा बाई',
    mobile: '9784332211',
    alternateMobile: '',
    category: 'आंगनवाड़ी सहायिका',
    address: 'उप स्वास्थ्य केंद्र के पास',
    remark: 'मातृ एवं शिशु स्वास्थ्य जानकारी',
  },
  {
    villageId: 'sundarpur',
    villageName: 'सुंदरपुर',
    name: 'गोपाल दास बैरागी',
    mobile: '9512345678',
    alternateMobile: '',
    category: 'ई-मित्र / सीएससी संचालक',
    address: 'पंचायत भवन परिसर',
    remark: 'आधार, जनाधार, पेंशन एवं सरकारी योजनाएं',
  },
  {
    villageId: 'kalyanpur',
    villageName: 'कल्याणपुर',
    name: 'कैलाश मेघवाल',
    mobile: '9678901234',
    alternateMobile: '',
    category: 'वाहन चालक (पिकअप/ट्रॉली)',
    address: 'बड़ा चौराहा',
    remark: 'सामान ढुलाई व कृषि माल परिवहन',
  },
];

export const COMMON_CATEGORIES = [
  'किसान (Farmer)',
  'किराना व्यापारी (Grocery)',
  'शिक्षक (Teacher)',
  'कृषि यंत्र मिस्त्री (Mechanic)',
  'इलेक्ट्रीशियन / प्लंबर (Technician)',
  'डेयरी संचालक (Dairy)',
  'वाहन चालक (Driver)',
  'सिलाई / दर्जी (Tailor)',
  'सीएससी / ई-मित्र केंद्र (CSC / Cyber)',
  'बढ़ई / कारपेंटर (Carpenter)',
  'राजमिस्त्री / निर्माण (Mason)',
  'पशु चिकित्सक / एआई वर्कर (Veterinary)',
  'दवा विक्रेता (Medical Store)',
  'व्यापारी / दुकानदार (Shopkeeper)',
  'अन्य (Other)',
];
